name: build packages for openwrt 23.05.4

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget liblua5.1-0-dev
 
      - name: obtains the sdk and config
        run: |
          curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-sdk-23.05.4-lantiq-xway_gcc-12.3.0_musl.Linux-x86_64.tar.xz | tar -J -x
          curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-imagebuilder-23.05.4-lantiq-xway.Linux-x86_64.tar.xz | tar -J -x
          #cp openwrt-imagebuilder*/.config openwrt-sdk-*/
          
      - name: build packages
        run: |
          cd openwrt-sdk-*

          echo "src-git custom https://github.com/olivluca/danube-voip-test" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds uninstall sofia-sip
          ./scripts/feeds install -p custom -f sofia-sip
          make defconfig
          echo "CONFIG_PACKAGE_svd=m" >> .config
          echo "CONFIG_PACKAGE_luci-app-svd=m" >> .config
          echo "CONFIG_PACKAGE_sofia-sip=m" >> .config
          #make -j1 V=s package/ltq-tapi/compile
          make -j1 V=s package/luci-app-svd/compile
      - name: build custom image
        run: |
          cp openwrt-sdk*/bin/packages/mips_24kc/custom/*.ipk openwrt-imagebuilder-*/packages/
          cd openwrt-imagebuilder-*
          make image PROFILE=arcadyan_arv7518pw PACKAGES="base-files br2684ctl busybox ca-bundle cgi-io dnsmasq dropbear firewall4 fstools fwtool getrandom hostapd-common iw iwinfo jansson4 jshn jsonfilter kernel kmod-ath kmod-ath9k kmod-ath9k-common kmod-atm kmod-cfg80211 kmod-crypto-acompress kmod-crypto-aead kmod-crypto-ccm kmod-crypto-cmac kmod-crypto-crc32c kmod-crypto-ctr kmod-crypto-gcm kmod-crypto-gf128 kmod-crypto-ghash kmod-crypto-hash kmod-crypto-hmac kmod-crypto-manager kmod-crypto-null kmod-crypto-rng kmod-crypto-seqiv kmod-crypto-sha512 kmod-gpio-button-hotplug kmod-leds-gpio kmod-lib-crc-ccitt kmod-lib-crc32c kmod-lib-lzo kmod-ltq-atm-danube kmod-ltq-ifxos kmod-ltq-tapi kmod-ltq-vmmc kmod-mac80211 kmod-nf-conntrack kmod-nf-conntrack6 kmod-nf-flow kmod-nf-log kmod-nf-log6 kmod-nf-nat kmod-nf-reject kmod-nf-reject6 kmod-nfnetlink kmod-nft-core kmod-nft-fib kmod-nft-nat kmod-nft-offload kmod-nls-base kmod-owl-loader kmod-ppp kmod-pppoa kmod-pppoe kmod-pppox kmod-random-core kmod-slhc kmod-usb-core kmod-usb-dwc2 kmod-usb-ledtrig-usbport kmod-usb-roles libblobmsg-json20230523 libc libgcc1 libiwinfo-data libiwinfo20230701 libjson-c5 libjson-script20230523 liblucihttp-ucode liblucihttp0 libmbedtls12 libmnl0 libnftnl11 libnl-tiny1 libpthread libubox20230523 libubus20230605 libuci20130104 libuclient20201210 libucode20230711 libustream-mbedtls20201210 linux-atm logd luci luci-app-firewall luci-app-opkg luci-base luci-light luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ipv6 luci-proto-ppp luci-ssl luci-theme-bootstrap mtd netifd nftables-json odhcp6c odhcpd-ipv6only openwrt-keyring opkg ppp ppp-mod-pppoa ppp-mod-pppoe procd procd-seccomp procd-ujail px5g-mbedtls rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns rpcd-mod-ucode sofia-sip svd swconfig ubi-utils ubox ubus ubusd uci uclient-fetch ucode ucode-mod-fs ucode-mod-html ucode-mod-math ucode-mod-nl80211 ucode-mod-rtnl ucode-mod-ubus ucode-mod-uci ucode-mod-uloop uhttpd uhttpd-mod-ubus urandom-seed urngd usign wireless-regdb wpad-basic-mbedtls luci-app-svd -ltq-adsl-app -ltq-dsl-base -kmod-ltq-adsl-danube -kmod-ltq-adsl-danube-fw-a -kmod-ltq-adsl-danube-mei -kmod-ltq-atm-danube"
          
      - uses: actions/Upload-artifact@v4
        with:
          name: packages-23.05.4
          path: openwrt-sdk-*/bin/
          
      - uses: actions/Upload-artifact@v4
        with:
          name: image-23.05.4
          path: openwrt-imagebuilder-*/bin/

