name: build packages for openwrt 23.05.4

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget liblua5.1-0-dev
 
      - name: obtains the sdk and config
        run: |
          curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-sdk-23.05.4-lantiq-xway_gcc-12.3.0_musl.Linux-x86_64.tar.xz | tar -J -x
          #curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-imagebuilder-23.05.4-lantiq-xway.Linux-x86_64.tar.xz | tar -J -x
          #cp openwrt-imagebuilder*/.config openwrt-sdk-*/
          
      - name: build packages
        run: |
          cd openwrt-sdk-*

          echo "src-git custom https://github.com/olivluca/danube-voip-test" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds uninstall sofia-sip
          ./scripts/feeds install -p custom -f sofia-sip
          make defconfig
          echo "CONFIG_PACKAGE_svd=m" >> .config
          echo "CONFIG_PACKAGE_luci-app-svd=m" >> .config
          echo "CONFIG_PACKAGE_sofia-sip=m" >> .config
          #make -j1 V=s package/ltq-tapi/compile
          make -j1 V=s package/luci-app-svd/compile
     
      - uses: actions/Upload-artifact@v4
        with:
          name: packages-23.05.4
          path: openwrt-sdk-*/bin/
          

